name = "tat-certificate-system"
compatibility_date = "2026-03-18"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "tat-certificate-db"
database_id = "922aeed2-2b33-491c-8dcc-fc3ab7b3ff34"
preview_database_id = "301096f9-e82f-47b7-8f3f-76440f59de4e"
migrations_dir = "migrations"
